version: '3.3'

services:
  nginx:
    image: dos-api-nginx:latest
    volumes:
    - "web_root:/var/www/dos-api:ro"
    - "certs:/etc/letsencrypt:ro"
    ports:
    - "80:80"
    restart: always
    environment:
      ENV:
    
  certbot:
    image: dos-api-certbot:latest
    volumes:
    - "web_root:/var/www/dos-api"
    - "certs:/etc/letsencrypt"
    restart: always
    environment:
      ENV:

  dos-api-app_v0-0-1:
    depends_on:
    - nginx
    image: dos-api-app:v0.0.1
    ports:
    - "8086:8086"

  dos-api-app_v0-0-2:
    depends_on:
    - nginx
    image: dos-api-app:v0.0.2
    ports:
    - "8087:8086"
 
  dos-api-app_v0-0-3:
    depends_on:
    - nginx
    image: dos-api-app:latest
    ports:
    - "8088:8086"
    
volumes:
  web_root:
  certs:
