---
# Install docker on ubuntu hosts
# Following instructions at https://docs.docker.com/engine/installation/linux/ubuntulinux/

- name: Install docker
  hosts: all
  gather_facts: true
  become: True
  vars:
    docker_repos: "deb https://apt.dockerproject.org/repo ubuntu-xenial main"
  tasks:
    - name: install https
      apt: 
          name: apt-transport-https
          update_cache: yes
          
    - name: install ca certs
      apt: 
          name: ca-certificates
          update_cache: yes
          
    - name: Add the new GPG key
      shell: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    
    - name: add docker repos
      apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-xenial main' state=present
    
    - name: get recent docker from new repos
      apt: 
          update_cache: yes
          
    - name: install docker package 
      apt:
          name: docker-engine
          
    - name: install docker package 
      apt:
          name: docker-compose

    - name: install pip
      apt:
          name: python-pip

    - name: install docker-py
      pip: name=docker-py
    
    - name: add user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes