---
- name: Provision EC2 environment
  hosts: localhost
  vars:
    region:  eu-west-2
    instance_type: t2.micro
    count: 1
  tasks:
  - name: get subnet ID
    ec2_vpc_subnet_facts:
      filters:
          "tag:subnet": dmz
          "tag:env": "{{ env }}"
      register: dmz_subnet
  - ec2_vpc_net_facts:
      filters:
        "tag:env": "{{ env }}"
      register: vpc
  - name: ec2 keypair
    ec2_key: "name={{ env_name }} key_material={{ item }} region={{ region }}"
    with_file: ~/.ssh/id_rsa.pub
  - name: web security group
    ec2_group:
      name: web
      description: allow http and https access
      region: "{{ region }}"
      vpc_id: "{{ vpc.id }}"
      rules:
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: 0.0.0.0/0
  - name: ssh security group
    ec2_group:
      name: ssh
      description: allow ssh access
      region: "{{ region }}"
      vpc_id: "{{ vpc.id }}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
  - name: outbound security group
    ec2_group:
      name: outbound
      description: allow outbound connections to the internet
      region: "{{ region }}"
      vpc_id: "{{ vpc.id }}"
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0
  - name: Get the ubuntu xenial ebs ssd AMI
    ec2_ami_find:
      name: "ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-*"
      region: "{{ region }}"
      sort: name
      sort_order: descending
      sort_end: 1
      no_result_action: fail
    register: ubuntu_image
  - set_fact: "ami={{ ubuntu_image.results[0].ami_id }}"
  - name: start the instances
    ec2:
      region: "{{ region }}"
      image: "{{ ami }}"
      instance_type: "{{ instance_type }}"
      key_name: mykey
      group: [web, ssh, outbound]
      instance_tags: { type: nginx, env: "{{ env_name }}" }
      exact_count: "{{ count }}"
      count_tag: { type: nginx }
      vpc_subnet_id: "{{ dmz_subnet.id }}"
      wait: yes
    register: ec2
  - name: add the instance to web and production groups
    add_host: hostname={{ item.public_dns_name }} groups=nginx,{{ env_name }}
    with_items: "{{ ec2.tagged_instances }}"
    when: item.public_dns_name is defined
  - name: wait for ssh server to be running
    wait_for: host={{ item.public_dns_name }} port=22 search_regex=OpenSSH
    with_items: "{{  ec2.tagged_instances }}"
    when: item.public_dns_name is defined

- name: configure servers
  hosts: all
  become: True
  gather_facts: False
  pre_tasks:
    - name: install python
      raw: apt-get install -y python-minimal